version: '3.8'
services:
  apache-php:
    container_name: apache-php
    build: .
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
      - ./jomnam2.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jomnam2
      MYSQL_USER: sakda
      MYSQL_PASSWORD: 1234
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 100000000
    depends_on:
      - db
volumes:
  dbdata:
