create table team_rating2 ( 
	gid serial not null,
	cid text,
	item111 numeric,
	item121 numeric,
	item122 numeric,
	item211 numeric,
	item212 numeric,
	item221 numeric,
	item231 numeric,
	item232 numeric,
	item311 numeric,
	item312 numeric,
	item3131 numeric,
	item3132 numeric,
	item321 numeric,
	item322 numeric,
	item331 numeric,
	item411 numeric,
	item412 numeric,
	item421 numeric,
	item511 numeric,
	item512 numeric,
	item513 numeric,
	item611 numeric,
	item612 numeric,
	item621 numeric,
	item622 numeric,
	item711 numeric,
	item712 numeric,
	item721 numeric,
	item722 numeric,
	item811 numeric,
	item812 numeric,
	item911 numeric,
	item921 numeric,
	item922 numeric,
	item1011 numeric,
	item1012 numeric
)


CREATE TABLE `panel_survey` (
  `id` int NOT NULL AUTO_INCREMENT,
  `province` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT 'จังหวัด',
  `amphur` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT 'อำเภอ',
  `tambon` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL COMMENT 'ตำบล',
  `village_no` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'หมู่ที่',
  `village_name` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT 'หมู่บ้าน',
  `txt` text COMMENT 'รายละเอียด',
  `lat` DOUBLE(16,6) COMMENT 'ละติจูด',
  `lon` DOUBLE(16, 6) COMMENT 'ลองจิจูด',
  `survey_date` date DEFAULT NULL COMMENT 'วันที่รายงาน',
  `surveyer` text COMMENT 'ผู้รายงาน',
  `cid` varchar(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ;